; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llvm-extract -func=single_bb_vscale %s | llc -mtriple=aarch64-linux-gnu -mattr=+sve2 | FileCheck %s --check-prefix=SVE2-SINGLE
; RUN: llvm-extract -func=single_bb_vscale %s | llc -mtriple=riscv64 -mattr=+v | FileCheck %s --check-prefix=RVV-SINGLE
define <vscale x 2 x i64> @single_bb_vscale(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b) {
; SVE2-SINGLE-LABEL: single_bb_vscale:
; SVE2-SINGLE:       // %bb.0:
; SVE2-SINGLE-NEXT:    smulh z0.d, z0.d, z1.d
; SVE2-SINGLE-NEXT:    ret
;
; RVV-SINGLE-LABEL: single_bb_vscale:
; RVV-SINGLE:       # %bb.0:
; RVV-SINGLE-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RVV-SINGLE-NEXT:    vmulh.vv v8, v8, v10
; RVV-SINGLE-NEXT:    ret
  %a.ext = sext <vscale x 2 x i64> %a to <vscale x 2 x i128>
  %b.ext = sext <vscale x 2 x i64> %b to <vscale x 2 x i128>
  %mul = mul <vscale x 2 x i128> %a.ext, %b.ext
  %shr = lshr <vscale x 2 x i128> %mul, splat(i128 64)
  %trunc = trunc <vscale x 2 x i128> %shr to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %trunc
}

; Both SVE/RVV crash in backend:
;   LLVM ERROR: Scalarization of scalable vectors is not supported.
; RUN: llvm-extract -func=invalid_vscale %s | not --crash llc -mtriple=aarch64-linux-gnu -mattr=+sve2 2>&1 | FileCheck %s --check-prefix=CRASH-SCALABLE-VECTOR-SCALARIZATION
; RUN: llvm-extract -func=invalid_vscale %s | not --crash llc -mtriple=riscv64 -mattr=+v 2>&1 | FileCheck %s --check-prefix=CRASH-SCALABLE-VECTOR-SCALARIZATION
; CRASH-SCALABLE-VECTOR-SCALARIZATION: LLVM ERROR: Scalarization of scalable vectors is not supported.
define <vscale x 2 x i64> @invalid_vscale(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b) {
  %a.ext = sext <vscale x 2 x i64> %a to <vscale x 2 x i128>
  %b.ext = sext <vscale x 2 x i64> %b to <vscale x 2 x i128>
  %mul = mul <vscale x 2 x i128> %a.ext, %b.ext
  %add = add <vscale x 2 x i128> %mul, %mul
  %shr = lshr <vscale x 2 x i128> %add, splat(i128 64)
  %trunc = trunc <vscale x 2 x i128> %shr to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %trunc
}

; RUN: llvm-extract -func=single_bb_vscale_multiple_uses %s | llc -mtriple=aarch64-linux-gnu -mattr=+sve2 | FileCheck %s --check-prefix=SVE2-MULTI
; RUN: llvm-extract -func=single_bb_vscale_multiple_uses %s | llc -mtriple=riscv64 -mattr=+v | FileCheck %s --check-prefix=RVV-MULTI
define <vscale x 2 x i64> @single_bb_vscale_multiple_uses(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b, <vscale x 2 x i64> %c) {
; SVE2-MULTI-LABEL: single_bb_vscale_multiple_uses:
; SVE2-MULTI:       // %bb.0:
; SVE2-MULTI-NEXT:    smulh z1.d, z0.d, z1.d
; SVE2-MULTI-NEXT:    smulh z0.d, z0.d, z2.d
; SVE2-MULTI-NEXT:    add z0.d, z1.d, z0.d
; SVE2-MULTI-NEXT:    ret
;
; RVV-MULTI-LABEL: single_bb_vscale_multiple_uses:
; RVV-MULTI:       # %bb.0:
; RVV-MULTI-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RVV-MULTI-NEXT:    vmulh.vv v10, v8, v10
; RVV-MULTI-NEXT:    vmulh.vv v8, v8, v12
; RVV-MULTI-NEXT:    vadd.vv v8, v10, v8
; RVV-MULTI-NEXT:    ret
  %a.ext = sext <vscale x 2 x i64> %a to <vscale x 2 x i128>
  %b.ext = sext <vscale x 2 x i64> %b to <vscale x 2 x i128>
  %c.ext = sext <vscale x 2 x i64> %c to <vscale x 2 x i128>
  %mul.ab = mul <vscale x 2 x i128> %a.ext, %b.ext
  %shr.ab = lshr <vscale x 2 x i128> %mul.ab, splat(i128 64)
  %trunc.ab = trunc <vscale x 2 x i128> %shr.ab to <vscale x 2 x i64>
  %mul.ac = mul <vscale x 2 x i128> %a.ext, %c.ext
  %shr.ac = lshr <vscale x 2 x i128> %mul.ac, splat(i128 64)
  %trunc.ac = trunc <vscale x 2 x i128> %shr.ac to <vscale x 2 x i64>
  %ret = add <vscale x 2 x i64> %trunc.ab, %trunc.ac
  ret <vscale x 2 x i64> %ret
}

; RUN: llvm-extract -func=multiple_bbs_vscale %s | llc -mtriple=aarch64-linux-gnu -mattr=+sve2 | FileCheck %s --check-prefix=SVE2-MULTIBBS
; RUN: llvm-extract -func=multiple_bbs_vscale %s | not --crash llc -mtriple=riscv64 -mattr=+v 2>&1 | FileCheck %s --check-prefix=CRASH-SCALABLE-VECTOR-TYPE-LEGALIZATION
; CRASH-SCALABLE-VECTOR-TYPE-LEGALIZATION: LLVM ERROR: Don't know how to legalize this scalable vector type
; Crashes RVV, works on SVE2
define <vscale x 2 x i64> @multiple_bbs_vscale(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b) {
; SVE2-MULTIBBS-LABEL: multiple_bbs_vscale:
; SVE2-MULTIBBS:       // %bb.0: // %bb0
; SVE2-MULTIBBS-NEXT:    smulh z0.d, z0.d, z1.d
; SVE2-MULTIBBS-NEXT:    ret
bb0:
  %a.ext = sext <vscale x 2 x i64> %a to <vscale x 2 x i128>
  %b.ext = sext <vscale x 2 x i64> %b to <vscale x 2 x i128>
  br label %bb1
bb1:
  %mul = mul <vscale x 2 x i128> %a.ext, %b.ext
  %shr = lshr <vscale x 2 x i128> %mul, splat(i128 64)
  %trunc = trunc <vscale x 2 x i128> %shr to <vscale x 2 x i64>
  ret <vscale x 2 x i64> %trunc
}


declare void @foo(<vscale x 2 x i64>)
declare <vscale x 2 x i64> @bar()

; RUN: llvm-extract -func=loop_vscale -func=foo -func=bar %s | llc -mtriple=aarch64-linux-gnu -mattr=+sve2 | FileCheck %s --check-prefix=SVE2-LOOP
; RUN: llvm-extract -func=loop_vscale -func=foo -func=bar %s | not --crash llc -mtriple=riscv64 -mattr=+v 2>&1 | FileCheck %s --check-prefix=CRASH-SCALABLE-VECTOR-TYPE-LEGALIZATION
; Crashes RVV, works on SVE2
define <vscale x 2 x i64> @loop_vscale(<vscale x 2 x i64> %a) {
; SVE2-LOOP-LABEL: loop_vscale:
; SVE2-LOOP:       // %bb.0: // %entry
; SVE2-LOOP-NEXT:    str x29, [sp, #-32]! // 8-byte Folded Spill
; SVE2-LOOP-NEXT:    stp x30, x19, [sp, #16] // 16-byte Folded Spill
; SVE2-LOOP-NEXT:    addvl sp, sp, #-2
; SVE2-LOOP-NEXT:    str z9, [sp] // 16-byte Folded Spill
; SVE2-LOOP-NEXT:    str z8, [sp, #1, mul vl] // 16-byte Folded Spill
; SVE2-LOOP-NEXT:    .cfi_escape 0x0f, 0x08, 0x8f, 0x20, 0x92, 0x2e, 0x00, 0x40, 0x1e, 0x22 // sp + 32 + 16 * VG
; SVE2-LOOP-NEXT:    .cfi_offset w19, -8
; SVE2-LOOP-NEXT:    .cfi_offset w30, -16
; SVE2-LOOP-NEXT:    .cfi_offset w29, -32
; SVE2-LOOP-NEXT:    .cfi_escape 0x10, 0x48, 0x0a, 0x92, 0x2e, 0x00, 0x11, 0x78, 0x1e, 0x22, 0x11, 0x60, 0x22 // $d8 @ cfa - 8 * VG - 32
; SVE2-LOOP-NEXT:    .cfi_escape 0x10, 0x49, 0x0a, 0x92, 0x2e, 0x00, 0x11, 0x70, 0x1e, 0x22, 0x11, 0x60, 0x22 // $d9 @ cfa - 16 * VG - 32
; SVE2-LOOP-NEXT:    mov z8.d, z0.d
; SVE2-LOOP-NEXT:    mov w19, #64 // =0x40
; SVE2-LOOP-NEXT:  .LBB0_1: // %header
; SVE2-LOOP-NEXT:    // =>This Inner Loop Header: Depth=1
; SVE2-LOOP-NEXT:    bl bar
; SVE2-LOOP-NEXT:    smulh z9.d, z8.d, z0.d
; SVE2-LOOP-NEXT:    mov z0.d, z9.d
; SVE2-LOOP-NEXT:    bl foo
; SVE2-LOOP-NEXT:    subs x19, x19, #1
; SVE2-LOOP-NEXT:    b.ne .LBB0_1
; SVE2-LOOP-NEXT:  // %bb.2: // %exit
; SVE2-LOOP-NEXT:    mov z0.d, z9.d
; SVE2-LOOP-NEXT:    ldr z9, [sp] // 16-byte Folded Reload
; SVE2-LOOP-NEXT:    ldr z8, [sp, #1, mul vl] // 16-byte Folded Reload
; SVE2-LOOP-NEXT:    addvl sp, sp, #2
; SVE2-LOOP-NEXT:    ldp x30, x19, [sp, #16] // 16-byte Folded Reload
; SVE2-LOOP-NEXT:    ldr x29, [sp], #32 // 8-byte Folded Reload
; SVE2-LOOP-NEXT:    ret
entry:
  %a.ext = sext <vscale x 2 x i64> %a to <vscale x 2 x i128>
  br label %header

header:
  %iv = phi i64 [0, %entry], [%iv.next, %header]
  %iv.next = add i64 %iv, 1
  %b = call <vscale x 2 x i64> @bar()
  %b.ext = sext <vscale x 2 x i64> %b to <vscale x 2 x i128>
  %mul = mul <vscale x 2 x i128> %a.ext, %b.ext
  %shr = lshr <vscale x 2 x i128> %mul, splat(i128 64)
  %trunc = trunc <vscale x 2 x i128> %shr to <vscale x 2 x i64>
  call void @foo(<vscale x 2 x i64> %trunc)
  %ec = icmp eq i64 %iv.next, 64
  br i1 %ec, label %exit, label %header

exit:
  ret <vscale x 2 x i64> %trunc
}

; RUN: llvm-extract -func=single_bb_fixed %s | llc -mtriple=aarch64-linux-gnu -mattr=+sve2 | FileCheck %s --check-prefix=SVE2-FIXED-SINGLE
; RUN: llvm-extract -func=single_bb_fixed %s | llc -mtriple=riscv64 -mattr=+v | FileCheck %s --check-prefix=RVV-FIXED-SINGLE
; RUN: llvm-extract -func=single_bb_fixed %s | llc -mtriple=x86_64-unknown-linux-gnu -mattr=+avx512ifma,+avx512vl | FileCheck %s --check-prefix=X86-FIXED-SINGLE
define <4 x i64> @single_bb_fixed(<4 x i64> %a, <4 x i64> %b) {
; SVE2-FIXED-SINGLE-LABEL: single_bb_fixed:
; SVE2-FIXED-SINGLE:       // %bb.0:
; SVE2-FIXED-SINGLE-NEXT:    ushr v1.2d, v1.2d, #12
; SVE2-FIXED-SINGLE-NEXT:    ushr v0.2d, v0.2d, #12
; SVE2-FIXED-SINGLE-NEXT:    ushr v3.2d, v3.2d, #12
; SVE2-FIXED-SINGLE-NEXT:    ushr v2.2d, v2.2d, #12
; SVE2-FIXED-SINGLE-NEXT:    umulh z1.d, z1.d, z3.d
; SVE2-FIXED-SINGLE-NEXT:    umulh z0.d, z0.d, z2.d
; SVE2-FIXED-SINGLE-NEXT:    // kill: def $q1 killed $q1 killed $z1
; SVE2-FIXED-SINGLE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; SVE2-FIXED-SINGLE-NEXT:    ret
;
; RVV-FIXED-SINGLE-LABEL: single_bb_fixed:
; RVV-FIXED-SINGLE:       # %bb.0:
; RVV-FIXED-SINGLE-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RVV-FIXED-SINGLE-NEXT:    vsrl.vi v8, v8, 12
; RVV-FIXED-SINGLE-NEXT:    vsrl.vi v10, v10, 12
; RVV-FIXED-SINGLE-NEXT:    vmulhu.vv v8, v8, v10
; RVV-FIXED-SINGLE-NEXT:    ret
;
; X86-FIXED-SINGLE-LABEL: single_bb_fixed:
; X86-FIXED-SINGLE:       # %bb.0:
; X86-FIXED-SINGLE-NEXT:    vpsrlq $12, %ymm0, %ymm2
; X86-FIXED-SINGLE-NEXT:    vpsrlq $12, %ymm1, %ymm3
; X86-FIXED-SINGLE-NEXT:    vpsrlq $44, %ymm0, %ymm0
; X86-FIXED-SINGLE-NEXT:    vpmuludq %ymm3, %ymm0, %ymm4
; X86-FIXED-SINGLE-NEXT:    vpmuludq %ymm3, %ymm2, %ymm3
; X86-FIXED-SINGLE-NEXT:    vpsrlq $32, %ymm3, %ymm3
; X86-FIXED-SINGLE-NEXT:    vpaddq %ymm3, %ymm4, %ymm3
; X86-FIXED-SINGLE-NEXT:    vpsrlq $32, %ymm3, %ymm4
; X86-FIXED-SINGLE-NEXT:    vpxor %xmm5, %xmm5, %xmm5
; X86-FIXED-SINGLE-NEXT:    vpblendd {{.*#+}} ymm3 = ymm3[0],ymm5[1],ymm3[2],ymm5[3],ymm3[4],ymm5[5],ymm3[6],ymm5[7]
; X86-FIXED-SINGLE-NEXT:    vpsrlq $44, %ymm1, %ymm1
; X86-FIXED-SINGLE-NEXT:    vpmuludq %ymm1, %ymm2, %ymm2
; X86-FIXED-SINGLE-NEXT:    vpaddq %ymm3, %ymm2, %ymm2
; X86-FIXED-SINGLE-NEXT:    vpsrlq $32, %ymm2, %ymm2
; X86-FIXED-SINGLE-NEXT:    vpmuludq %ymm1, %ymm0, %ymm0
; X86-FIXED-SINGLE-NEXT:    vpaddq %ymm4, %ymm0, %ymm0
; X86-FIXED-SINGLE-NEXT:    vpaddq %ymm2, %ymm0, %ymm0
; X86-FIXED-SINGLE-NEXT:    retq
  %a.shifted = lshr <4 x i64> %a, splat(i64 12)
  %b.shifted = lshr <4 x i64> %b, splat(i64 12)
  %a.ext = sext <4 x i64> %a.shifted to <4 x i128>
  %b.ext = sext <4 x i64> %b.shifted to <4 x i128>
  %mul = mul <4 x i128> %a.ext, %b.ext
  %shr = lshr <4 x i128> %mul, splat(i128 64)
  %trunc = trunc <4 x i128> %shr to <4 x i64>
  ret <4 x i64> %trunc
}

; RUN: llvm-extract -func=single_bb_fixed_multiple_uses %s | llc -mtriple=aarch64-linux-gnu -mattr=+sve2 | FileCheck %s --check-prefix=SVE2-FIXED-MULTI
; RUN: llvm-extract -func=single_bb_fixed_multiple_uses %s | llc -mtriple=riscv64 -mattr=+v | FileCheck %s --check-prefix=RVV-FIXED-MULTI
; RUN: llvm-extract -func=single_bb_fixed_multiple_uses %s | llc -mtriple=x86_64-unknown-linux-gnu -mattr=+avx512ifma,+avx512vl | FileCheck %s --check-prefix=X86-FIXED-MULTI
define <4 x i64> @single_bb_fixed_multiple_uses(<4 x i64> %a, <4 x i64> %b, <4 x i64> %c) {
; SVE2-FIXED-MULTI-LABEL: single_bb_fixed_multiple_uses:
; SVE2-FIXED-MULTI:       // %bb.0:
; SVE2-FIXED-MULTI-NEXT:    ushr v0.2d, v0.2d, #12
; SVE2-FIXED-MULTI-NEXT:    ushr v1.2d, v1.2d, #12
; SVE2-FIXED-MULTI-NEXT:    ushr v2.2d, v2.2d, #12
; SVE2-FIXED-MULTI-NEXT:    ushr v3.2d, v3.2d, #12
; SVE2-FIXED-MULTI-NEXT:    ushr v4.2d, v4.2d, #12
; SVE2-FIXED-MULTI-NEXT:    ushr v5.2d, v5.2d, #12
; SVE2-FIXED-MULTI-NEXT:    umulh z2.d, z0.d, z2.d
; SVE2-FIXED-MULTI-NEXT:    umulh z3.d, z1.d, z3.d
; SVE2-FIXED-MULTI-NEXT:    umulh z1.d, z1.d, z5.d
; SVE2-FIXED-MULTI-NEXT:    umulh z0.d, z0.d, z4.d
; SVE2-FIXED-MULTI-NEXT:    add v1.2d, v3.2d, v1.2d
; SVE2-FIXED-MULTI-NEXT:    add v0.2d, v2.2d, v0.2d
; SVE2-FIXED-MULTI-NEXT:    ret
;
; RVV-FIXED-MULTI-LABEL: single_bb_fixed_multiple_uses:
; RVV-FIXED-MULTI:       # %bb.0:
; RVV-FIXED-MULTI-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RVV-FIXED-MULTI-NEXT:    vsrl.vi v10, v10, 12
; RVV-FIXED-MULTI-NEXT:    vsrl.vi v8, v8, 12
; RVV-FIXED-MULTI-NEXT:    vsrl.vi v12, v12, 12
; RVV-FIXED-MULTI-NEXT:    vmulhu.vv v10, v8, v10
; RVV-FIXED-MULTI-NEXT:    vmulhu.vv v8, v8, v12
; RVV-FIXED-MULTI-NEXT:    vadd.vv v8, v10, v8
; RVV-FIXED-MULTI-NEXT:    ret
;
; X86-FIXED-MULTI-LABEL: single_bb_fixed_multiple_uses:
; X86-FIXED-MULTI:       # %bb.0:
; X86-FIXED-MULTI-NEXT:    vpsrlq $12, %ymm0, %ymm3
; X86-FIXED-MULTI-NEXT:    vpsrlq $12, %ymm1, %ymm4
; X86-FIXED-MULTI-NEXT:    vpsrlq $12, %ymm2, %ymm5
; X86-FIXED-MULTI-NEXT:    vpsrlq $44, %ymm0, %ymm0
; X86-FIXED-MULTI-NEXT:    vpmuludq %ymm4, %ymm0, %ymm6
; X86-FIXED-MULTI-NEXT:    vpmuludq %ymm4, %ymm3, %ymm4
; X86-FIXED-MULTI-NEXT:    vpsrlq $32, %ymm4, %ymm4
; X86-FIXED-MULTI-NEXT:    vpaddq %ymm4, %ymm6, %ymm4
; X86-FIXED-MULTI-NEXT:    vpsrlq $32, %ymm4, %ymm6
; X86-FIXED-MULTI-NEXT:    vpxor %xmm7, %xmm7, %xmm7
; X86-FIXED-MULTI-NEXT:    vpblendd {{.*#+}} ymm4 = ymm4[0],ymm7[1],ymm4[2],ymm7[3],ymm4[4],ymm7[5],ymm4[6],ymm7[7]
; X86-FIXED-MULTI-NEXT:    vpsrlq $44, %ymm1, %ymm1
; X86-FIXED-MULTI-NEXT:    vpmuludq %ymm1, %ymm3, %ymm8
; X86-FIXED-MULTI-NEXT:    vpaddq %ymm4, %ymm8, %ymm4
; X86-FIXED-MULTI-NEXT:    vpsrlq $32, %ymm4, %ymm4
; X86-FIXED-MULTI-NEXT:    vpmuludq %ymm1, %ymm0, %ymm1
; X86-FIXED-MULTI-NEXT:    vpaddq %ymm6, %ymm1, %ymm1
; X86-FIXED-MULTI-NEXT:    vpaddq %ymm4, %ymm1, %ymm1
; X86-FIXED-MULTI-NEXT:    vpmuludq %ymm5, %ymm0, %ymm4
; X86-FIXED-MULTI-NEXT:    vpmuludq %ymm5, %ymm3, %ymm5
; X86-FIXED-MULTI-NEXT:    vpsrlq $32, %ymm5, %ymm5
; X86-FIXED-MULTI-NEXT:    vpaddq %ymm5, %ymm4, %ymm4
; X86-FIXED-MULTI-NEXT:    vpsrlq $32, %ymm4, %ymm5
; X86-FIXED-MULTI-NEXT:    vpblendd {{.*#+}} ymm4 = ymm4[0],ymm7[1],ymm4[2],ymm7[3],ymm4[4],ymm7[5],ymm4[6],ymm7[7]
; X86-FIXED-MULTI-NEXT:    vpsrlq $44, %ymm2, %ymm2
; X86-FIXED-MULTI-NEXT:    vpmuludq %ymm2, %ymm3, %ymm3
; X86-FIXED-MULTI-NEXT:    vpaddq %ymm4, %ymm3, %ymm3
; X86-FIXED-MULTI-NEXT:    vpsrlq $32, %ymm3, %ymm3
; X86-FIXED-MULTI-NEXT:    vpmuludq %ymm2, %ymm0, %ymm0
; X86-FIXED-MULTI-NEXT:    vpaddq %ymm5, %ymm0, %ymm0
; X86-FIXED-MULTI-NEXT:    vpaddq %ymm3, %ymm0, %ymm0
; X86-FIXED-MULTI-NEXT:    vpaddq %ymm0, %ymm1, %ymm0
; X86-FIXED-MULTI-NEXT:    retq
  %a.shifted = lshr <4 x i64> %a, splat(i64 12)
  %b.shifted = lshr <4 x i64> %b, splat(i64 12)
  %c.shifted = lshr <4 x i64> %c, splat(i64 12)
  %a.ext = sext <4 x i64> %a.shifted to <4 x i128>
  %b.ext = sext <4 x i64> %b.shifted to <4 x i128>
  %c.ext = sext <4 x i64> %c.shifted to <4 x i128>
  %mul.ab = mul <4 x i128> %a.ext, %b.ext
  %shr.ab = lshr <4 x i128> %mul.ab, splat(i128 64)
  %trunc.ab = trunc <4 x i128> %shr.ab to <4 x i64>
  %mul.ac = mul <4 x i128> %a.ext, %c.ext
  %shr.ac = lshr <4 x i128> %mul.ac, splat(i128 64)
  %trunc.ac = trunc <4 x i128> %shr.ac to <4 x i64>
  %ret = add <4 x i64> %trunc.ab, %trunc.ac
  ret <4 x i64> %ret
}

; RUN: llvm-extract -func=multiple_bbs_fixed %s | llc -mtriple=aarch64-linux-gnu -mattr=+sve2 | FileCheck %s --check-prefix=SVE2-FIXED-MULTIBBS
; RUN: llvm-extract -func=multiple_bbs_fixed %s | llc -mtriple=riscv64 -mattr=+v | FileCheck %s --check-prefix=RVV-FIXED-MULTIBBS
; RUN: llvm-extract -func=multiple_bbs_fixed %s | llc -mtriple=x86_64-unknown-linux-gnu -mattr=+avx512ifma,+avx512vl | FileCheck %s --check-prefix=X86-FIXED-MULTIBBS
define <4 x i64> @multiple_bbs_fixed(<4 x i64> %a, <4 x i64> %b) {
; SVE2-FIXED-MULTIBBS-LABEL: multiple_bbs_fixed:
; SVE2-FIXED-MULTIBBS:       // %bb.0: // %bb0
; SVE2-FIXED-MULTIBBS-NEXT:    ushr v1.2d, v1.2d, #12
; SVE2-FIXED-MULTIBBS-NEXT:    ushr v0.2d, v0.2d, #12
; SVE2-FIXED-MULTIBBS-NEXT:    ushr v3.2d, v3.2d, #12
; SVE2-FIXED-MULTIBBS-NEXT:    ushr v2.2d, v2.2d, #12
; SVE2-FIXED-MULTIBBS-NEXT:    umulh z1.d, z1.d, z3.d
; SVE2-FIXED-MULTIBBS-NEXT:    umulh z0.d, z0.d, z2.d
; SVE2-FIXED-MULTIBBS-NEXT:    // kill: def $q1 killed $q1 killed $z1
; SVE2-FIXED-MULTIBBS-NEXT:    // kill: def $q0 killed $q0 killed $z0
; SVE2-FIXED-MULTIBBS-NEXT:    ret
;
; RVV-FIXED-MULTIBBS-LABEL: multiple_bbs_fixed:
; RVV-FIXED-MULTIBBS:       # %bb.0: # %bb0
; RVV-FIXED-MULTIBBS-NEXT:    addi sp, sp, -64
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_def_cfa_offset 64
; RVV-FIXED-MULTIBBS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; RVV-FIXED-MULTIBBS-NEXT:    sd s0, 48(sp) # 8-byte Folded Spill
; RVV-FIXED-MULTIBBS-NEXT:    sd s1, 40(sp) # 8-byte Folded Spill
; RVV-FIXED-MULTIBBS-NEXT:    sd s2, 32(sp) # 8-byte Folded Spill
; RVV-FIXED-MULTIBBS-NEXT:    sd s3, 24(sp) # 8-byte Folded Spill
; RVV-FIXED-MULTIBBS-NEXT:    sd s4, 16(sp) # 8-byte Folded Spill
; RVV-FIXED-MULTIBBS-NEXT:    sd s5, 8(sp) # 8-byte Folded Spill
; RVV-FIXED-MULTIBBS-NEXT:    sd s6, 0(sp) # 8-byte Folded Spill
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_offset ra, -8
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_offset s0, -16
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_offset s1, -24
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_offset s2, -32
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_offset s3, -40
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_offset s4, -48
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_offset s5, -56
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_offset s6, -64
; RVV-FIXED-MULTIBBS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RVV-FIXED-MULTIBBS-NEXT:    vsrl.vi v8, v8, 12
; RVV-FIXED-MULTIBBS-NEXT:    vmv.x.s s0, v8
; RVV-FIXED-MULTIBBS-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; RVV-FIXED-MULTIBBS-NEXT:    vslidedown.vi v12, v8, 2
; RVV-FIXED-MULTIBBS-NEXT:    vmv.x.s s3, v12
; RVV-FIXED-MULTIBBS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; RVV-FIXED-MULTIBBS-NEXT:    vslidedown.vi v8, v8, 1
; RVV-FIXED-MULTIBBS-NEXT:    vmv.x.s s2, v8
; RVV-FIXED-MULTIBBS-NEXT:    vslidedown.vi v8, v12, 1
; RVV-FIXED-MULTIBBS-NEXT:    vmv.x.s a0, v8
; RVV-FIXED-MULTIBBS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RVV-FIXED-MULTIBBS-NEXT:    vsrl.vi v8, v10, 12
; RVV-FIXED-MULTIBBS-NEXT:    vmv.x.s s1, v8
; RVV-FIXED-MULTIBBS-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; RVV-FIXED-MULTIBBS-NEXT:    vslidedown.vi v10, v8, 2
; RVV-FIXED-MULTIBBS-NEXT:    vmv.x.s s5, v10
; RVV-FIXED-MULTIBBS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; RVV-FIXED-MULTIBBS-NEXT:    vslidedown.vi v8, v8, 1
; RVV-FIXED-MULTIBBS-NEXT:    vmv.x.s s4, v8
; RVV-FIXED-MULTIBBS-NEXT:    vslidedown.vi v8, v10, 1
; RVV-FIXED-MULTIBBS-NEXT:    vmv.x.s a2, v8
; RVV-FIXED-MULTIBBS-NEXT:    li a1, 0
; RVV-FIXED-MULTIBBS-NEXT:    li a3, 0
; RVV-FIXED-MULTIBBS-NEXT:    call __multi3
; RVV-FIXED-MULTIBBS-NEXT:    mv s6, a1
; RVV-FIXED-MULTIBBS-NEXT:    mv a0, s3
; RVV-FIXED-MULTIBBS-NEXT:    li a1, 0
; RVV-FIXED-MULTIBBS-NEXT:    mv a2, s5
; RVV-FIXED-MULTIBBS-NEXT:    li a3, 0
; RVV-FIXED-MULTIBBS-NEXT:    call __multi3
; RVV-FIXED-MULTIBBS-NEXT:    mv s3, a1
; RVV-FIXED-MULTIBBS-NEXT:    mv a0, s2
; RVV-FIXED-MULTIBBS-NEXT:    li a1, 0
; RVV-FIXED-MULTIBBS-NEXT:    mv a2, s4
; RVV-FIXED-MULTIBBS-NEXT:    li a3, 0
; RVV-FIXED-MULTIBBS-NEXT:    call __multi3
; RVV-FIXED-MULTIBBS-NEXT:    mv s2, a1
; RVV-FIXED-MULTIBBS-NEXT:    mv a0, s0
; RVV-FIXED-MULTIBBS-NEXT:    li a1, 0
; RVV-FIXED-MULTIBBS-NEXT:    mv a2, s1
; RVV-FIXED-MULTIBBS-NEXT:    li a3, 0
; RVV-FIXED-MULTIBBS-NEXT:    call __multi3
; RVV-FIXED-MULTIBBS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; RVV-FIXED-MULTIBBS-NEXT:    vmv.s.x v9, s2
; RVV-FIXED-MULTIBBS-NEXT:    vmv.s.x v8, a1
; RVV-FIXED-MULTIBBS-NEXT:    vmv.s.x v10, s3
; RVV-FIXED-MULTIBBS-NEXT:    vmv.s.x v11, s6
; RVV-FIXED-MULTIBBS-NEXT:    vslideup.vi v8, v9, 1
; RVV-FIXED-MULTIBBS-NEXT:    vslideup.vi v10, v11, 1
; RVV-FIXED-MULTIBBS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RVV-FIXED-MULTIBBS-NEXT:    vslideup.vi v8, v10, 2
; RVV-FIXED-MULTIBBS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; RVV-FIXED-MULTIBBS-NEXT:    ld s0, 48(sp) # 8-byte Folded Reload
; RVV-FIXED-MULTIBBS-NEXT:    ld s1, 40(sp) # 8-byte Folded Reload
; RVV-FIXED-MULTIBBS-NEXT:    ld s2, 32(sp) # 8-byte Folded Reload
; RVV-FIXED-MULTIBBS-NEXT:    ld s3, 24(sp) # 8-byte Folded Reload
; RVV-FIXED-MULTIBBS-NEXT:    ld s4, 16(sp) # 8-byte Folded Reload
; RVV-FIXED-MULTIBBS-NEXT:    ld s5, 8(sp) # 8-byte Folded Reload
; RVV-FIXED-MULTIBBS-NEXT:    ld s6, 0(sp) # 8-byte Folded Reload
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_restore ra
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_restore s0
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_restore s1
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_restore s2
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_restore s3
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_restore s4
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_restore s5
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_restore s6
; RVV-FIXED-MULTIBBS-NEXT:    addi sp, sp, 64
; RVV-FIXED-MULTIBBS-NEXT:    .cfi_def_cfa_offset 0
; RVV-FIXED-MULTIBBS-NEXT:    ret
;
; X86-FIXED-MULTIBBS-LABEL: multiple_bbs_fixed:
; X86-FIXED-MULTIBBS:       # %bb.0: # %bb0
; X86-FIXED-MULTIBBS-NEXT:    vpsrlq $12, %ymm0, %ymm0
; X86-FIXED-MULTIBBS-NEXT:    vpsrlq $12, %ymm1, %ymm1
; X86-FIXED-MULTIBBS-NEXT:    vextracti128 $1, %ymm0, %xmm2
; X86-FIXED-MULTIBBS-NEXT:    vpextrq $1, %xmm2, %rax
; X86-FIXED-MULTIBBS-NEXT:    vmovq %xmm2, %rdi
; X86-FIXED-MULTIBBS-NEXT:    vpextrq $1, %xmm0, %rsi
; X86-FIXED-MULTIBBS-NEXT:    vmovq %xmm0, %rcx
; X86-FIXED-MULTIBBS-NEXT:    vextracti128 $1, %ymm1, %xmm0
; X86-FIXED-MULTIBBS-NEXT:    vpextrq $1, %xmm0, %rdx
; X86-FIXED-MULTIBBS-NEXT:    vmovq %xmm0, %r11
; X86-FIXED-MULTIBBS-NEXT:    vpextrq $1, %xmm1, %r10
; X86-FIXED-MULTIBBS-NEXT:    vmovq %xmm1, %r9
; X86-FIXED-MULTIBBS-NEXT:    mulq %rdx
; X86-FIXED-MULTIBBS-NEXT:    movq %rdx, %r8
; X86-FIXED-MULTIBBS-NEXT:    movq %rdi, %rax
; X86-FIXED-MULTIBBS-NEXT:    mulq %r11
; X86-FIXED-MULTIBBS-NEXT:    movq %rdx, %rdi
; X86-FIXED-MULTIBBS-NEXT:    movq %rsi, %rax
; X86-FIXED-MULTIBBS-NEXT:    mulq %r10
; X86-FIXED-MULTIBBS-NEXT:    movq %rdx, %rsi
; X86-FIXED-MULTIBBS-NEXT:    movq %rcx, %rax
; X86-FIXED-MULTIBBS-NEXT:    mulq %r9
; X86-FIXED-MULTIBBS-NEXT:    vmovq %rdx, %xmm0
; X86-FIXED-MULTIBBS-NEXT:    vmovq %rsi, %xmm1
; X86-FIXED-MULTIBBS-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; X86-FIXED-MULTIBBS-NEXT:    vmovq %rdi, %xmm1
; X86-FIXED-MULTIBBS-NEXT:    vmovq %r8, %xmm2
; X86-FIXED-MULTIBBS-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm2[0]
; X86-FIXED-MULTIBBS-NEXT:    vinserti128 $1, %xmm1, %ymm0, %ymm0
; X86-FIXED-MULTIBBS-NEXT:    retq
bb0:
  %a.shifted = lshr <4 x i64> %a, splat(i64 12)
  %b.shifted = lshr <4 x i64> %b, splat(i64 12)
  %a.ext = sext <4 x i64> %a.shifted to <4 x i128>
  %b.ext = sext <4 x i64> %b.shifted to <4 x i128>
  br label %bb1
bb1:
  %mul = mul <4 x i128> %a.ext, %b.ext
  %shr = lshr <4 x i128> %mul, splat(i128 64)
  %trunc = trunc <4 x i128> %shr to <4 x i64>
  ret <4 x i64> %trunc
}

declare void @foo_fixed(<4 x i64>)
declare <4 x i64> @bar_fixed()

; RUN: llvm-extract -func=loop_fixed -func=foo_fixed -func=bar_fixed %s | llc -mtriple=aarch64-linux-gnu -mattr=+sve2 | FileCheck %s --check-prefix=SVE2-FIXED-LOOP
; RUN: llvm-extract -func=loop_fixed -func=foo_fixed -func=bar_fixed %s | llc -mtriple=riscv64 -mattr=+v | FileCheck %s --check-prefix=RVV-FIXED-LOOP
; RUN: llvm-extract -func=loop_fixed -func=foo_fixed -func=bar_fixed %s | llc -mtriple=x86_64-unknown-linux-gnu -mattr=+avx512ifma,+avx512vl | FileCheck %s --check-prefix=X86-FIXED-LOOP
define <4 x i64> @loop_fixed(<4 x i64> %a) {
; SVE2-FIXED-LOOP-LABEL: loop_fixed:
; SVE2-FIXED-LOOP:       // %bb.0: // %entry
; SVE2-FIXED-LOOP-NEXT:    str x29, [sp, #-32]! // 8-byte Folded Spill
; SVE2-FIXED-LOOP-NEXT:    stp x30, x19, [sp, #16] // 16-byte Folded Spill
; SVE2-FIXED-LOOP-NEXT:    addvl sp, sp, #-4
; SVE2-FIXED-LOOP-NEXT:    .cfi_escape 0x0f, 0x09, 0x8f, 0x20, 0x92, 0x2e, 0x00, 0x11, 0x20, 0x1e, 0x22 // sp + 32 + 32 * VG
; SVE2-FIXED-LOOP-NEXT:    .cfi_offset w19, -8
; SVE2-FIXED-LOOP-NEXT:    .cfi_offset w30, -16
; SVE2-FIXED-LOOP-NEXT:    .cfi_offset w29, -32
; SVE2-FIXED-LOOP-NEXT:    ushr v1.2d, v1.2d, #12
; SVE2-FIXED-LOOP-NEXT:    ushr v0.2d, v0.2d, #12
; SVE2-FIXED-LOOP-NEXT:    mov w19, #64 // =0x40
; SVE2-FIXED-LOOP-NEXT:    str z1, [sp, #3, mul vl] // 16-byte Folded Spill
; SVE2-FIXED-LOOP-NEXT:    str z0, [sp, #2, mul vl] // 16-byte Folded Spill
; SVE2-FIXED-LOOP-NEXT:  .LBB0_1: // %header
; SVE2-FIXED-LOOP-NEXT:    // =>This Inner Loop Header: Depth=1
; SVE2-FIXED-LOOP-NEXT:    bl bar_fixed
; SVE2-FIXED-LOOP-NEXT:    ushr v1.2d, v1.2d, #12
; SVE2-FIXED-LOOP-NEXT:    ldr z2, [sp, #3, mul vl] // 16-byte Folded Reload
; SVE2-FIXED-LOOP-NEXT:    ushr v0.2d, v0.2d, #12
; SVE2-FIXED-LOOP-NEXT:    umulh z2.d, z2.d, z1.d
; SVE2-FIXED-LOOP-NEXT:    ldr z1, [sp, #2, mul vl] // 16-byte Folded Reload
; SVE2-FIXED-LOOP-NEXT:    umulh z0.d, z1.d, z0.d
; SVE2-FIXED-LOOP-NEXT:    mov v1.16b, v2.16b
; SVE2-FIXED-LOOP-NEXT:    str z2, [sp, #1, mul vl] // 16-byte Folded Spill
; SVE2-FIXED-LOOP-NEXT:    str z0, [sp] // 16-byte Folded Spill
; SVE2-FIXED-LOOP-NEXT:    // kill: def $q0 killed $q0 killed $z0
; SVE2-FIXED-LOOP-NEXT:    bl foo_fixed
; SVE2-FIXED-LOOP-NEXT:    subs x19, x19, #1
; SVE2-FIXED-LOOP-NEXT:    b.ne .LBB0_1
; SVE2-FIXED-LOOP-NEXT:  // %bb.2: // %exit
; SVE2-FIXED-LOOP-NEXT:    ldr z0, [sp] // 16-byte Folded Reload
; SVE2-FIXED-LOOP-NEXT:    ldr z1, [sp, #1, mul vl] // 16-byte Folded Reload
; SVE2-FIXED-LOOP-NEXT:    // kill: def $q0 killed $q0 killed $z0
; SVE2-FIXED-LOOP-NEXT:    // kill: def $q1 killed $q1 killed $z1
; SVE2-FIXED-LOOP-NEXT:    addvl sp, sp, #4
; SVE2-FIXED-LOOP-NEXT:    ldp x30, x19, [sp, #16] // 16-byte Folded Reload
; SVE2-FIXED-LOOP-NEXT:    ldr x29, [sp], #32 // 8-byte Folded Reload
; SVE2-FIXED-LOOP-NEXT:    ret
;
; RVV-FIXED-LOOP-LABEL: loop_fixed:
; RVV-FIXED-LOOP:       # %bb.0: # %entry
; RVV-FIXED-LOOP-NEXT:    addi sp, sp, -96
; RVV-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 96
; RVV-FIXED-LOOP-NEXT:    sd ra, 88(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    sd s0, 80(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    sd s1, 72(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    sd s2, 64(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    sd s3, 56(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    sd s4, 48(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    sd s5, 40(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    sd s6, 32(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    sd s7, 24(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    sd s8, 16(sp) # 8-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    .cfi_offset ra, -8
; RVV-FIXED-LOOP-NEXT:    .cfi_offset s0, -16
; RVV-FIXED-LOOP-NEXT:    .cfi_offset s1, -24
; RVV-FIXED-LOOP-NEXT:    .cfi_offset s2, -32
; RVV-FIXED-LOOP-NEXT:    .cfi_offset s3, -40
; RVV-FIXED-LOOP-NEXT:    .cfi_offset s4, -48
; RVV-FIXED-LOOP-NEXT:    .cfi_offset s5, -56
; RVV-FIXED-LOOP-NEXT:    .cfi_offset s6, -64
; RVV-FIXED-LOOP-NEXT:    .cfi_offset s7, -72
; RVV-FIXED-LOOP-NEXT:    .cfi_offset s8, -80
; RVV-FIXED-LOOP-NEXT:    csrr a0, vlenb
; RVV-FIXED-LOOP-NEXT:    slli a0, a0, 1
; RVV-FIXED-LOOP-NEXT:    sub sp, sp, a0
; RVV-FIXED-LOOP-NEXT:    .cfi_escape 0x0f, 0x0e, 0x72, 0x00, 0x11, 0xe0, 0x00, 0x22, 0x11, 0x02, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 96 + 2 * vlenb
; RVV-FIXED-LOOP-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RVV-FIXED-LOOP-NEXT:    vsrl.vi v8, v8, 12
; RVV-FIXED-LOOP-NEXT:    vmv.x.s s0, v8
; RVV-FIXED-LOOP-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; RVV-FIXED-LOOP-NEXT:    vslidedown.vi v10, v8, 2
; RVV-FIXED-LOOP-NEXT:    vmv.x.s s1, v10
; RVV-FIXED-LOOP-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; RVV-FIXED-LOOP-NEXT:    vslidedown.vi v8, v8, 1
; RVV-FIXED-LOOP-NEXT:    vmv.x.s s2, v8
; RVV-FIXED-LOOP-NEXT:    vslidedown.vi v8, v10, 1
; RVV-FIXED-LOOP-NEXT:    vmv.x.s s3, v8
; RVV-FIXED-LOOP-NEXT:    li s8, 64
; RVV-FIXED-LOOP-NEXT:  .LBB0_1: # %header
; RVV-FIXED-LOOP-NEXT:    # =>This Inner Loop Header: Depth=1
; RVV-FIXED-LOOP-NEXT:    call bar_fixed
; RVV-FIXED-LOOP-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RVV-FIXED-LOOP-NEXT:    vsrl.vi v8, v8, 12
; RVV-FIXED-LOOP-NEXT:    vmv.x.s s4, v8
; RVV-FIXED-LOOP-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; RVV-FIXED-LOOP-NEXT:    vslidedown.vi v10, v8, 1
; RVV-FIXED-LOOP-NEXT:    vmv.x.s s5, v10
; RVV-FIXED-LOOP-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; RVV-FIXED-LOOP-NEXT:    vslidedown.vi v8, v8, 2
; RVV-FIXED-LOOP-NEXT:    vmv.x.s s6, v8
; RVV-FIXED-LOOP-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; RVV-FIXED-LOOP-NEXT:    vslidedown.vi v8, v8, 1
; RVV-FIXED-LOOP-NEXT:    vmv.x.s a2, v8
; RVV-FIXED-LOOP-NEXT:    mv a0, s3
; RVV-FIXED-LOOP-NEXT:    li a1, 0
; RVV-FIXED-LOOP-NEXT:    li a3, 0
; RVV-FIXED-LOOP-NEXT:    call __multi3
; RVV-FIXED-LOOP-NEXT:    mv s7, a1
; RVV-FIXED-LOOP-NEXT:    mv a0, s1
; RVV-FIXED-LOOP-NEXT:    li a1, 0
; RVV-FIXED-LOOP-NEXT:    mv a2, s6
; RVV-FIXED-LOOP-NEXT:    li a3, 0
; RVV-FIXED-LOOP-NEXT:    call __multi3
; RVV-FIXED-LOOP-NEXT:    mv s6, a1
; RVV-FIXED-LOOP-NEXT:    mv a0, s2
; RVV-FIXED-LOOP-NEXT:    li a1, 0
; RVV-FIXED-LOOP-NEXT:    mv a2, s5
; RVV-FIXED-LOOP-NEXT:    li a3, 0
; RVV-FIXED-LOOP-NEXT:    call __multi3
; RVV-FIXED-LOOP-NEXT:    mv s5, a1
; RVV-FIXED-LOOP-NEXT:    mv a0, s0
; RVV-FIXED-LOOP-NEXT:    li a1, 0
; RVV-FIXED-LOOP-NEXT:    mv a2, s4
; RVV-FIXED-LOOP-NEXT:    li a3, 0
; RVV-FIXED-LOOP-NEXT:    call __multi3
; RVV-FIXED-LOOP-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; RVV-FIXED-LOOP-NEXT:    vmv.s.x v9, s5
; RVV-FIXED-LOOP-NEXT:    vmv.s.x v8, a1
; RVV-FIXED-LOOP-NEXT:    vmv.s.x v12, s6
; RVV-FIXED-LOOP-NEXT:    vmv.s.x v10, s7
; RVV-FIXED-LOOP-NEXT:    vslideup.vi v8, v9, 1
; RVV-FIXED-LOOP-NEXT:    vslideup.vi v12, v10, 1
; RVV-FIXED-LOOP-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RVV-FIXED-LOOP-NEXT:    vslideup.vi v8, v12, 2
; RVV-FIXED-LOOP-NEXT:    addi a0, sp, 16
; RVV-FIXED-LOOP-NEXT:    vs2r.v v8, (a0) # vscale x 16-byte Folded Spill
; RVV-FIXED-LOOP-NEXT:    call foo_fixed
; RVV-FIXED-LOOP-NEXT:    addi s8, s8, -1
; RVV-FIXED-LOOP-NEXT:    bnez s8, .LBB0_1
; RVV-FIXED-LOOP-NEXT:  # %bb.2: # %exit
; RVV-FIXED-LOOP-NEXT:    addi a0, sp, 16
; RVV-FIXED-LOOP-NEXT:    vl2r.v v8, (a0) # vscale x 16-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    csrr a0, vlenb
; RVV-FIXED-LOOP-NEXT:    slli a0, a0, 1
; RVV-FIXED-LOOP-NEXT:    add sp, sp, a0
; RVV-FIXED-LOOP-NEXT:    .cfi_def_cfa sp, 96
; RVV-FIXED-LOOP-NEXT:    ld ra, 88(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    ld s0, 80(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    ld s1, 72(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    ld s2, 64(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    ld s3, 56(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    ld s4, 48(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    ld s5, 40(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    ld s6, 32(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    ld s7, 24(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    ld s8, 16(sp) # 8-byte Folded Reload
; RVV-FIXED-LOOP-NEXT:    .cfi_restore ra
; RVV-FIXED-LOOP-NEXT:    .cfi_restore s0
; RVV-FIXED-LOOP-NEXT:    .cfi_restore s1
; RVV-FIXED-LOOP-NEXT:    .cfi_restore s2
; RVV-FIXED-LOOP-NEXT:    .cfi_restore s3
; RVV-FIXED-LOOP-NEXT:    .cfi_restore s4
; RVV-FIXED-LOOP-NEXT:    .cfi_restore s5
; RVV-FIXED-LOOP-NEXT:    .cfi_restore s6
; RVV-FIXED-LOOP-NEXT:    .cfi_restore s7
; RVV-FIXED-LOOP-NEXT:    .cfi_restore s8
; RVV-FIXED-LOOP-NEXT:    addi sp, sp, 96
; RVV-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 0
; RVV-FIXED-LOOP-NEXT:    ret
;
; X86-FIXED-LOOP-LABEL: loop_fixed:
; X86-FIXED-LOOP:       # %bb.0: # %entry
; X86-FIXED-LOOP-NEXT:    pushq %r15
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 16
; X86-FIXED-LOOP-NEXT:    pushq %r14
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 24
; X86-FIXED-LOOP-NEXT:    pushq %r13
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 32
; X86-FIXED-LOOP-NEXT:    pushq %r12
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 40
; X86-FIXED-LOOP-NEXT:    pushq %rbx
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 48
; X86-FIXED-LOOP-NEXT:    subq $32, %rsp
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 80
; X86-FIXED-LOOP-NEXT:    .cfi_offset %rbx, -48
; X86-FIXED-LOOP-NEXT:    .cfi_offset %r12, -40
; X86-FIXED-LOOP-NEXT:    .cfi_offset %r13, -32
; X86-FIXED-LOOP-NEXT:    .cfi_offset %r14, -24
; X86-FIXED-LOOP-NEXT:    .cfi_offset %r15, -16
; X86-FIXED-LOOP-NEXT:    vpsrlq $12, %ymm0, %ymm0
; X86-FIXED-LOOP-NEXT:    vextracti128 $1, %ymm0, %xmm1
; X86-FIXED-LOOP-NEXT:    vpextrq $1, %xmm1, %rbx
; X86-FIXED-LOOP-NEXT:    vmovq %xmm1, %r14
; X86-FIXED-LOOP-NEXT:    vpextrq $1, %xmm0, %r15
; X86-FIXED-LOOP-NEXT:    vmovq %xmm0, %r12
; X86-FIXED-LOOP-NEXT:    movl $64, %r13d
; X86-FIXED-LOOP-NEXT:    .p2align 4
; X86-FIXED-LOOP-NEXT:  .LBB0_1: # %header
; X86-FIXED-LOOP-NEXT:    # =>This Inner Loop Header: Depth=1
; X86-FIXED-LOOP-NEXT:    callq bar_fixed@PLT
; X86-FIXED-LOOP-NEXT:    vpsrlq $12, %ymm0, %ymm0
; X86-FIXED-LOOP-NEXT:    vpextrq $1, %xmm0, %r8
; X86-FIXED-LOOP-NEXT:    vmovq %xmm0, %rdi
; X86-FIXED-LOOP-NEXT:    vextracti128 $1, %ymm0, %xmm0
; X86-FIXED-LOOP-NEXT:    vmovq %xmm0, %rsi
; X86-FIXED-LOOP-NEXT:    vpextrq $1, %xmm0, %rcx
; X86-FIXED-LOOP-NEXT:    movq %rbx, %rax
; X86-FIXED-LOOP-NEXT:    mulq %rcx
; X86-FIXED-LOOP-NEXT:    movq %rdx, %rcx
; X86-FIXED-LOOP-NEXT:    movq %r14, %rax
; X86-FIXED-LOOP-NEXT:    mulq %rsi
; X86-FIXED-LOOP-NEXT:    movq %rdx, %rsi
; X86-FIXED-LOOP-NEXT:    movq %r12, %rax
; X86-FIXED-LOOP-NEXT:    mulq %rdi
; X86-FIXED-LOOP-NEXT:    movq %rdx, %rdi
; X86-FIXED-LOOP-NEXT:    movq %r15, %rax
; X86-FIXED-LOOP-NEXT:    mulq %r8
; X86-FIXED-LOOP-NEXT:    vmovq %rdx, %xmm0
; X86-FIXED-LOOP-NEXT:    vmovq %rdi, %xmm1
; X86-FIXED-LOOP-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; X86-FIXED-LOOP-NEXT:    vmovq %rsi, %xmm1
; X86-FIXED-LOOP-NEXT:    vmovq %rcx, %xmm2
; X86-FIXED-LOOP-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm2[0]
; X86-FIXED-LOOP-NEXT:    vinserti128 $1, %xmm1, %ymm0, %ymm0
; X86-FIXED-LOOP-NEXT:    vmovdqu %ymm0, (%rsp) # 32-byte Spill
; X86-FIXED-LOOP-NEXT:    callq foo_fixed@PLT
; X86-FIXED-LOOP-NEXT:    decq %r13
; X86-FIXED-LOOP-NEXT:    jne .LBB0_1
; X86-FIXED-LOOP-NEXT:  # %bb.2: # %exit
; X86-FIXED-LOOP-NEXT:    vmovups (%rsp), %ymm0 # 32-byte Reload
; X86-FIXED-LOOP-NEXT:    addq $32, %rsp
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 48
; X86-FIXED-LOOP-NEXT:    popq %rbx
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 40
; X86-FIXED-LOOP-NEXT:    popq %r12
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 32
; X86-FIXED-LOOP-NEXT:    popq %r13
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 24
; X86-FIXED-LOOP-NEXT:    popq %r14
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 16
; X86-FIXED-LOOP-NEXT:    popq %r15
; X86-FIXED-LOOP-NEXT:    .cfi_def_cfa_offset 8
; X86-FIXED-LOOP-NEXT:    retq
entry:
  %a.shifted = lshr <4 x i64> %a, splat(i64 12)
  %a.ext = sext <4 x i64> %a.shifted to <4 x i128>
  br label %header

header:
  %iv = phi i64 [0, %entry], [%iv.next, %header]
  %iv.next = add i64 %iv, 1
  %b = call <4 x i64> @bar_fixed()
  %b.shifted = lshr <4 x i64> %b, splat(i64 12)
  %b.ext = sext <4 x i64> %b.shifted to <4 x i128>
  %mul = mul <4 x i128> %a.ext, %b.ext
  %shr = lshr <4 x i128> %mul, splat(i128 64)
  %trunc = trunc <4 x i128> %shr to <4 x i64>
  call void @foo_fixed(<4 x i64> %trunc)
  %ec = icmp eq i64 %iv.next, 64
  br i1 %ec, label %exit, label %header

exit:
  ret <4 x i64> %trunc
}
