; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6

; Normally UTC script can't generate CHECKs if a given VPlan pass is run
; multiple times. However, --vplan-print-instance can be used to specify which
; one we're interested in.

; RUN: opt -passes=loop-vectorize -disable-output -vplan-print-after=VPlanTransforms::simplifyRecipes -vplan-print-instance=1 -vplan-print-vector-region-scope -force-vector-width=4 -vplan-verify-each < %s 2>&1 | FileCheck %s -check-prefixes=CHECK-FIRST
; RUN: opt -passes=loop-vectorize -disable-output -vplan-print-after=VPlanTransforms::simplifyRecipes -vplan-print-instance=2 -vplan-print-vector-region-scope -force-vector-width=4 -vplan-verify-each < %s 2>&1 | FileCheck %s -check-prefixes=CHECK-SECOND

define void @foo(ptr %ptr, i64 %n) {
; CHECK-FIRST-LABEL: VPlan for loop in 'foo'
; CHECK-FIRST:  VPlan ' for UF>=1' {
; CHECK-FIRST-EMPTY:
; CHECK-FIRST-NEXT:  ir-bb<entry>:
; CHECK-FIRST-NEXT:    EMIT vp<[[VP1:%[0-9]+]]> = EXPAND SCEV (1 smax %n)
; CHECK-FIRST-NEXT:  Successor(s): scalar.ph, vector.ph
; CHECK-FIRST-EMPTY:
; CHECK-FIRST-NEXT:  vector.ph:
; CHECK-FIRST-NEXT:  Successor(s): header
; CHECK-FIRST-EMPTY:
; CHECK-FIRST-NEXT:  header:
; CHECK-FIRST-NEXT:    EMIT-SCALAR ir<%iv> = phi [ ir<0>, vector.ph ], [ ir<%iv.next>, header ]
; CHECK-FIRST-NEXT:    EMIT ir<%gep> = getelementptr ir<%ptr>, ir<%iv>
; CHECK-FIRST-NEXT:    EMIT store ir<%iv>, ir<%gep>
; CHECK-FIRST-NEXT:    EMIT ir<%iv.next> = add nsw ir<%iv>, ir<1>
; CHECK-FIRST-NEXT:    EMIT ir<%exitcond> = icmp sge ir<%iv.next>, ir<%n>
; CHECK-FIRST-NEXT:    EMIT vp<[[VP2:%[0-9]+]]> = not ir<%exitcond>
; CHECK-FIRST-NEXT:    EMIT branch-on-cond ir<%exitcond>
; CHECK-FIRST-NEXT:  Successor(s): middle.block, header
; CHECK-FIRST-EMPTY:
; CHECK-FIRST-NEXT:  middle.block:
; CHECK-FIRST-NEXT:    EMIT vp<[[VP3:%[0-9]+]]> = extract-last-part ir<%iv.next>
; CHECK-FIRST-NEXT:    EMIT vp<[[VP4:%[0-9]+]]> = extract-last-lane vp<[[VP3]]>
; CHECK-FIRST-NEXT:  Successor(s): ir-bb<exit>, scalar.ph
; CHECK-FIRST-EMPTY:
; CHECK-FIRST-NEXT:  ir-bb<exit>:
; CHECK-FIRST-NEXT:  No successors
; CHECK-FIRST-EMPTY:
; CHECK-FIRST-NEXT:  scalar.ph:
; CHECK-FIRST-NEXT:    EMIT-SCALAR vp<[[VP5:%[0-9]+]]> = phi [ vp<[[VP4]]>, middle.block ], [ ir<0>, ir-bb<entry> ]
; CHECK-FIRST-NEXT:  Successor(s): ir-bb<header>
; CHECK-FIRST-EMPTY:
; CHECK-FIRST-NEXT:  ir-bb<header>:
; CHECK-FIRST-NEXT:    IR   %iv = phi i64 [ 0, %entry ], [ %iv.next, %header ] (extra operand: vp<[[VP5]]> from scalar.ph)
; CHECK-FIRST-NEXT:    IR   %gep = getelementptr i64, ptr %ptr, i64 %iv
; CHECK-FIRST-NEXT:    IR   store i64 %iv, ptr %gep, align 4
; CHECK-FIRST-NEXT:    IR   %iv.next = add nsw i64 %iv, 1
; CHECK-FIRST-NEXT:    IR   %exitcond = icmp slt i64 %iv.next, %n
; CHECK-FIRST-NEXT:  No successors
; CHECK-FIRST-NEXT:  }
;
; CHECK-SECOND-LABEL: VPlan for loop in 'foo'
; CHECK-SECOND-NEXT:  <x1> vector loop: {
; CHECK-SECOND-NEXT:  vp<[[VP5:%[0-9]+]]> = CANONICAL-IV
; CHECK-SECOND-EMPTY:
; CHECK-SECOND-NEXT:    vector.body:
; CHECK-SECOND-NEXT:      ir<%iv> = WIDEN-INDUCTION nsw ir<0>, ir<1>, vp<[[VP0:%[0-9]+]]>
; CHECK-SECOND-NEXT:      vp<[[VP6:%[0-9]+]]> = SCALAR-STEPS vp<[[VP5]]>, ir<1>, vp<[[VP0]]>
; CHECK-SECOND-NEXT:      CLONE ir<%gep> = getelementptr ir<%ptr>, vp<[[VP5]]>
; CHECK-SECOND-NEXT:      vp<[[VP7:%[0-9]+]]> = vector-pointer ir<%gep>, ir<1>
; CHECK-SECOND-NEXT:      WIDEN store ir<%gep>, ir<%iv>
; CHECK-SECOND-NEXT:      EMIT vp<%index.next> = add nuw vp<[[VP5]]>, vp<[[VP1:%[0-9]+]]>
; CHECK-SECOND-NEXT:      EMIT branch-on-count vp<%index.next>, vp<[[VP2:%[0-9]+]]>
; CHECK-SECOND-NEXT:    No successors
; CHECK-SECOND-NEXT:  }
; CHECK-SECOND-NEXT:  Successor(s): middle.block
;
entry:
  br label %header

header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %header ]
  %gep = getelementptr i64, ptr %ptr, i64 %iv
  store i64 %iv, ptr %gep
  %iv.next = add nsw i64 %iv, 1
  %exitcond = icmp slt i64 %iv.next, %n
  br i1 %exitcond, label %header, label %exit

exit:
  ret void
}
