; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt -disable-output < %s -p "vplan-test<predicator>" | FileCheck %s
declare i64 @llvm.vplan.test.lane()
define void @single_bb(ptr %a) {
; CHECK-LABEL: 'single_bb'
; CHECK-NEXT:  VPlan 'VPlan for single_bb for UF={1}' {
; CHECK-EMPTY:
; CHECK-NEXT:  bb0:
; CHECK-NEXT:    EMIT ir<%lane> = call ir<@llvm.vplan.test.lane>
; CHECK-NEXT:    EMIT ir<%gep> = getelementptr ir<%a>, ir<%lane>
; CHECK-NEXT:    EMIT store ir<%lane>, ir<%gep>
; CHECK-NEXT:    EMIT ret
; CHECK-NEXT:  No successors
; CHECK-NEXT:  }
; CHECK-EMPTY:
;
bb0:
  %lane = call i64 @llvm.vplan.test.lane()
  %gep = getelementptr i64, ptr %a, i64 %lane
  store i64 %lane, ptr %gep
  ret void
}

define void @diamond_phi(ptr %a) {
; CHECK-LABEL: 'diamond_phi'
; CHECK-NEXT:  VPlan 'VPlan for diamond_phi for UF={1}' {
; CHECK-EMPTY:
; CHECK-NEXT:  bb0:
; CHECK-NEXT:    EMIT ir<%lane> = call ir<@llvm.vplan.test.lane>
; CHECK-NEXT:    EMIT ir<%gep> = getelementptr ir<%a>, ir<%lane>
; CHECK-NEXT:    EMIT ir<%c0> = icmp sle ir<%lane>, ir<0>
; CHECK-NEXT:  Successor(s): bb2
; CHECK-EMPTY:
; CHECK-NEXT:  bb2:
; CHECK-NEXT:    EMIT [[VP1:vp<%.*>]] = not ir<%c0>
; CHECK-NEXT:    EMIT ir<%add2> = add ir<%lane>, ir<2>, [[VP1]]
; CHECK-NEXT:  Successor(s): bb1
; CHECK-EMPTY:
; CHECK-NEXT:  bb1:
; CHECK-NEXT:    EMIT ir<%add1> = add ir<%lane>, ir<1>, ir<%c0>
; CHECK-NEXT:  Successor(s): bb4
; CHECK-EMPTY:
; CHECK-NEXT:  bb4:
; CHECK-NEXT:    EMIT [[VP2:vp<%.*>]] = or [[VP1]], ir<%c0>
; CHECK-NEXT:    BLEND ir<%phi4> = ir<%add2> ir<%add1>/ir<%c0>
; CHECK-NEXT:    EMIT store ir<%phi4>, ir<%gep>, [[VP2]]
; CHECK-NEXT:    EMIT ret [[VP2]]
; CHECK-NEXT:  No successors
; CHECK-NEXT:  }
; CHECK-EMPTY:
;
bb0:
;          bb0
;         /  \
;       bb1  bb2
;         \  /
;          bb4
; TODO: bb4 should be unmasked.
  %lane = call i64 @llvm.vplan.test.lane()
  %gep = getelementptr i64, ptr %a, i64 %lane
  %c0 = icmp sle i64 %lane, 0
  br i1 %c0, label %bb1, label %bb2

bb1:
  %add1 = add i64 %lane, 1
  br label %bb4

bb2:
  %add2 = add i64 %lane, 2
  br label %bb4

bb4:
  %phi4 = phi i64 [%add1, %bb1], [%add2, %bb2]
  store i64 %phi4, ptr %gep
  ret void
}

define void @mask_reuse(ptr %a) {
; CHECK-LABEL: 'mask_reuse'
; CHECK-NEXT:  VPlan 'VPlan for mask_reuse for UF={1}' {
; CHECK-EMPTY:
; CHECK-NEXT:  bb0:
; CHECK-NEXT:    EMIT ir<%lane> = call ir<@llvm.vplan.test.lane>
; CHECK-NEXT:    EMIT ir<%gep> = getelementptr ir<%a>, ir<%lane>
; CHECK-NEXT:    EMIT ir<%c0> = icmp sle ir<%lane>, ir<0>
; CHECK-NEXT:    EMIT ir<%add0> = add ir<%lane>, ir<0>
; CHECK-NEXT:  Successor(s): bb1
; CHECK-EMPTY:
; CHECK-NEXT:  bb1:
; CHECK-NEXT:    EMIT ir<%add1> = add ir<%lane>, ir<1>, ir<%c0>
; CHECK-NEXT:    EMIT ir<%c1> = icmp sle ir<%lane>, ir<1>, ir<%c0>
; CHECK-NEXT:  Successor(s): bb2
; CHECK-EMPTY:
; CHECK-NEXT:  bb2:
; CHECK-NEXT:    EMIT [[VP1:vp<%.*>]] = logical-and ir<%c0>, ir<%c1>
; CHECK-NEXT:    EMIT ir<%add2> = add ir<%lane>, ir<2>, [[VP1]]
; CHECK-NEXT:  Successor(s): bb3
; CHECK-EMPTY:
; CHECK-NEXT:  bb3:
; CHECK-NEXT:    EMIT [[VP2:vp<%.*>]] = not ir<%c1>
; CHECK-NEXT:    EMIT [[VP3:vp<%.*>]] = logical-and ir<%c0>, [[VP2]]
; CHECK-NEXT:    EMIT [[VP4:vp<%.*>]] = or [[VP1]], [[VP3]]
; CHECK-NEXT:    BLEND ir<%phi3> = ir<%add2> ir<%add1>/[[VP3]]
; CHECK-NEXT:    EMIT ir<%add3> = add ir<%lane>, ir<3>, [[VP4]]
; CHECK-NEXT:  Successor(s): bb4
; CHECK-EMPTY:
; CHECK-NEXT:  bb4:
; CHECK-NEXT:    EMIT [[VP5:vp<%.*>]] = not ir<%c0>
; CHECK-NEXT:    EMIT [[VP6:vp<%.*>]] = or [[VP4]], [[VP5]]
; CHECK-NEXT:    BLEND ir<%phi4> = ir<%add3> ir<%add0>/[[VP5]]
; CHECK-NEXT:    EMIT store ir<%phi4>, ir<%gep>, [[VP6]]
; CHECK-NEXT:    EMIT ret [[VP6]]
; CHECK-NEXT:  No successors
; CHECK-NEXT:  }
; CHECK-EMPTY:
;
bb0:
;         bb0:
;         / \
;      bb1   \
;       /\    \
;     bb2 |   |
;      \  |   |
;       bb3  /
;         \ /
;         bb4
; TODO: bb3 can reuse bb1's mask and bb4 should be unmasked.
  %lane = call i64 @llvm.vplan.test.lane()
  %gep = getelementptr i64, ptr %a, i64 %lane
  %c0 = icmp sle i64 %lane, 0
  %add0 = add i64 %lane, 0
  br i1 %c0, label %bb1, label %bb4

bb1:
  %add1 = add i64 %lane, 1
  %c1 = icmp sle i64 %lane, 1
  br i1 %c1, label %bb2, label %bb3

bb2:
  %add2 = add i64 %lane, 2
  br label %bb3

bb3:
  %phi3 = phi i64 [%add1, %bb1], [%add2, %bb2]
  %add3 = add i64 %lane, 3
  br label %bb4

bb4:
  %phi4 = phi i64 [%add3, %bb3], [%add0, %bb0]
  store i64 %phi4, ptr %gep
  ret void
}

define void @optimized_mask(ptr %a) {
; CHECK-LABEL: 'optimized_mask'
; CHECK-NEXT:  VPlan 'VPlan for optimized_mask for UF={1}' {
; CHECK-EMPTY:
; CHECK-NEXT:  bb0:
; CHECK-NEXT:    EMIT ir<%lane> = call ir<@llvm.vplan.test.lane>
; CHECK-NEXT:    EMIT ir<%gep> = getelementptr ir<%a>, ir<%lane>
; CHECK-NEXT:    EMIT ir<%c0> = icmp sle ir<%lane>, ir<0>
; CHECK-NEXT:  Successor(s): bb6
; CHECK-EMPTY:
; CHECK-NEXT:  bb6:
; CHECK-NEXT:    EMIT [[VP1:vp<%.*>]] = not ir<%c0>
; CHECK-NEXT:    EMIT ir<%add6> = add ir<%lane>, ir<6>, [[VP1]]
; CHECK-NEXT:    EMIT ir<%c6> = icmp sle ir<%lane>, ir<6>, [[VP1]]
; CHECK-NEXT:  Successor(s): bb1
; CHECK-EMPTY:
; CHECK-NEXT:  bb1:
; CHECK-NEXT:    EMIT ir<%add1> = add ir<%lane>, ir<1>, ir<%c0>
; CHECK-NEXT:    EMIT ir<%c1> = icmp sle ir<%lane>, ir<1>, ir<%c0>
; CHECK-NEXT:  Successor(s): bb3
; CHECK-EMPTY:
; CHECK-NEXT:  bb3:
; CHECK-NEXT:    EMIT [[VP2:vp<%.*>]] = not ir<%c1>
; CHECK-NEXT:    EMIT [[VP3:vp<%.*>]] = logical-and ir<%c0>, [[VP2]]
; CHECK-NEXT:    EMIT ir<%add3> = add ir<%lane>, ir<3>, [[VP3]]
; CHECK-NEXT:    EMIT ir<%c3> = icmp sle ir<%lane>, ir<3>, [[VP3]]
; CHECK-NEXT:  Successor(s): bb2
; CHECK-EMPTY:
; CHECK-NEXT:  bb2:
; CHECK-NEXT:    EMIT [[VP4:vp<%.*>]] = logical-and ir<%c0>, ir<%c1>
; CHECK-NEXT:    EMIT ir<%add2> = add ir<%lane>, ir<2>, [[VP4]]
; CHECK-NEXT:  Successor(s): bb4
; CHECK-EMPTY:
; CHECK-NEXT:  bb4:
; CHECK-NEXT:    EMIT [[VP5:vp<%.*>]] = logical-and [[VP3]], ir<%c3>
; CHECK-NEXT:    EMIT [[VP6:vp<%.*>]] = or [[VP5]], [[VP4]]
; CHECK-NEXT:    BLEND ir<%phi4> = ir<%add3> ir<%add2>/[[VP4]]
; CHECK-NEXT:    EMIT ir<%add4> = add ir<%lane>, ir<4>, [[VP6]]
; CHECK-NEXT:  Successor(s): bb5
; CHECK-EMPTY:
; CHECK-NEXT:  bb5:
; CHECK-NEXT:    EMIT [[VP7:vp<%.*>]] = logical-and [[VP1]], ir<%c6>
; CHECK-NEXT:    EMIT [[VP8:vp<%.*>]] = or [[VP7]], [[VP6]]
; CHECK-NEXT:    EMIT [[VP9:vp<%.*>]] = not ir<%c3>
; CHECK-NEXT:    EMIT [[VP10:vp<%.*>]] = logical-and [[VP3]], [[VP9]]
; CHECK-NEXT:    EMIT [[VP11:vp<%.*>]] = or [[VP8]], [[VP10]]
; CHECK-NEXT:    BLEND ir<%phi5> = ir<%add6> ir<%add4>/[[VP6]] ir<%add3>/[[VP10]]
; CHECK-NEXT:    EMIT ir<%add5> = add ir<%lane>, ir<5>, [[VP11]]
; CHECK-NEXT:  Successor(s): bb7
; CHECK-EMPTY:
; CHECK-NEXT:  bb7:
; CHECK-NEXT:    EMIT [[VP12:vp<%.*>]] = not ir<%c6>
; CHECK-NEXT:    EMIT [[VP13:vp<%.*>]] = logical-and [[VP1]], [[VP12]]
; CHECK-NEXT:    EMIT [[VP14:vp<%.*>]] = or [[VP13]], [[VP11]]
; CHECK-NEXT:    BLEND ir<%phi7> = ir<%add6> ir<%add5>/[[VP11]]
; CHECK-NEXT:    EMIT store ir<%phi7>, ir<%gep>, [[VP14]]
; CHECK-NEXT:    EMIT ret [[VP14]]
; CHECK-NEXT:  No successors
; CHECK-NEXT:  }
; CHECK-EMPTY:
;
bb0:
;               bb0:
;              /   \
;             /     \
;          bb1       bb6
;          /  \      / |
;        bb2  bb3   /  /
;          \  /|   /  /
;           bb4|  /  /
;            \ | /  /
;             bb5  /
;               \ /
;               bb7
; TODO: bb5's mask shouldn't depend on c1/c3.
  %lane = call i64 @llvm.vplan.test.lane()
  %gep = getelementptr i64, ptr %a, i64 %lane
  %c0 = icmp sle i64 %lane, 0
  br i1 %c0, label %bb1, label %bb6

bb1:
  %add1 = add i64 %lane, 1
  %c1 = icmp sle i64 %lane, 1
  br i1 %c1, label %bb2, label %bb3

bb2:
  %add2 = add i64 %lane, 2
  br label %bb4

bb3:
  %add3 = add i64 %lane, 3
  %c3 = icmp sle i64 %lane, 3
  br i1 %c3, label %bb4, label %bb5

bb4:
  %phi4 = phi i64 [%add2, %bb2], [%add3, %bb3]
  %add4 = add i64 %lane, 4
  br label %bb5

bb5:
  %phi5 = phi i64 [%add4, %bb4], [%add3, %bb3], [%add6, %bb6]
  %add5 = add i64 %lane, 5
  br label %bb7

bb6:
  %add6 = add i64 %lane, 6
  %c6 = icmp sle i64 %lane, 6
  br i1 %c6, label %bb5, label %bb7

bb7:
  %phi7 = phi i64 [%add5, %bb5], [%add6, %bb6]
  store i64 %phi7, ptr %gep
  ret void
}
